stage_name: B1
epochs: 12
base_lr: 1.0e-06
refiner_lr: 1.0e-05
train_base: false
train_heads: false
train_film: false
train_refiner: true
refine_steps: 2
delta_scale: 0.12
use_film: true
film_subset:
  - T
heads_subset: null
baseline_fix_enable: false
enable_progress_bar: false
optuna:
  refiner_lr:
    type: float
    low: 1.0e-06
    high: 1.0e-03
    log: true
  delta_scale:
    type: float
    low: 0.05
    high: 0.2
  refine_steps:
    type: int
    low: 1
    high: 4
  model.encoder.params.width_mult:
    type: float
    low: 0.75
    high: 1.5
  model.encoder.params.depth_mult:
    type: float
    low: 0.8
    high: 1.5
  model.encoder.params.expand_ratio_scale:
    type: float
    low: 0.8
    high: 1.3
  model.encoder.params.se_ratio:
    type: float
    low: 0.15
    high: 0.35
  model.encoder.params.norm_groups:
    type: categorical
    choices: [4, 8, 16]
  model.shared_head_hidden_scale:
    type: float
    low: 0.4
    high: 0.8
  model.refiner.params.width_mult:
    type: float
    low: 0.75
    high: 1.5
  model.refiner.params.depth_mult:
    type: float
    low: 0.8
    high: 1.5
  model.refiner.params.expand_ratio_scale:
    type: float
    low: 0.8
    high: 1.3
  model.refiner.params.se_ratio:
    type: float
    low: 0.15
    high: 0.35
  model.refiner.params.norm_groups:
    type: categorical
    choices: [4, 8, 16]
  model.refiner.params.hidden_scale:
    type: float
    low: 0.4
    high: 0.8
  optimizer:
    type: categorical
    choices: [adamw, lion]
  optimizer_weight_decay:
    type: float
    low: 1.0e-06
    high: 1.0e-03
    log: true
  optimizer_beta1:
    type: float
    low: 0.85
    high: 0.99
  optimizer_beta2:
    type: float
    low: 0.9
    high: 0.9999
  scheduler_eta_min:
    type: float
    low: 1.0e-09
    high: 1.0e-06
    log: true
