stage_name: B1
epochs: 12
base_lr: 1.0e-06
refiner_lr: 1.0e-05
train_base: false
train_heads: false
train_film: false
train_refiner: true
refine_steps: 2
delta_scale: 0.12
use_film: true
film_subset:
  - T
heads_subset: null
baseline_fix_enable: false
enable_progress_bar: false
optuna:
  refiner_lr:
    type: float
    low: 1.0e-06
    high: 1.0e-03
    log: true
  delta_scale:
    type: float
    low: 0.05
    high: 0.2
  refine_steps:
    type: int
    low: 1
    high: 4
