stage_name: A
epochs: 20
base_lr: 0.0002
refiner_lr: 1.0e-06
train_base: true
train_heads: true
train_film: false
train_refiner: false
refine_steps: 0
delta_scale: 0.1
use_film: false
film_subset: null
heads_subset: null
baseline_fix_enable: false
enable_progress_bar: false
optuna:
  base_lr:
    type: float
    low: 1.0e-05
    high: 1.0e-03
    log: true
  epochs:
    type: int
    low: 10
    high: 40
  delta_scale:
    type: float
    low: 0.05
    high: 0.2
